server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/oris_test_sem2
    username: postgres
    password: reg123321reg
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  liquibase:
    enabled: false
  freemarker:
    template-loader-path: /WEB-INF/templates
    suffix: .ftl